services:
  mongodb:
    image: mongo:7.0
    environment:
    SPRING_DATA_MONGODB_URI: mongodb://admin:password@mongodb_old:27017/local?authSource=admin
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db